// MAKEHELP.BAT generated Help Map file.  Used by FBD.HPJ. 
 
// Commands (ID_* and IDM_*) 
#define HID_INDICATOR_TIME                      0x10069
#define HID_EXPLAIN                             0x1006C
#define HID_UPDATE_HASH                         0x10494
#define HID_UPDATE_GRPH                         0x10495
#define HID_YES                                 0x104C7
#define HID_UPDATE_SVARS                        0x104C9
#define HID_UPDATE_ALL                          0x104CA
#define HID_HINTBAR_HIDE                        0x104E6
#define HID_INSERT                              0x104ED
#define HID_CALCULATE                           0x1051D
#define HID_CANCEL_EDIT                         0x18000
#define HID_DRAWVECTOR_FIRST                    0x18001
#define HID_DRAWVECTOR_FORCE                    0x18001
#define HID_DRAWVECTOR_VELOCITY                 0x18002
#define HID_DRAWVECTOR_ACCELERATION             0x18003
#define HID_DRAWVECTOR_COMPONENT                0x18004
#define HID_DRAWVECTOR_DISPLACEMENT             0x18005
#define HID_DRAWVECTOR_LAST                     0x18005
#define HID_OBJECT_MOVETOFRONT                  0x18006
#define HID_OBJECT_MOVETOBACK                   0x18007
#define HID_OBJECT_MOVEFORWARD                  0x18008
#define HID_OBJECT_MOVEBACK                     0x18009
#define HID_EDIT_DELETE                         0x1800A
#define HID_VARIABLE_DELETE                     0x1800B
#define HID_HELP_OPTIONS                        0x1800C
#define HID_EDIT_PROPERTIES                     0x1800D
#define HID_DECOMPOSE_VECTOR                    0x1800E
#define HID_AUTHORMODE                          0x1800F
#define HID_EDIT_DUPLICATE                      0x18010
#define HID_VIEW_EXPCONTROL                     0x18011
#define HID_VIEW_OPTIONS                        0x18012
#define HID_POPUP_EDITVECTORTYPE                0x18013
#define HID_EDIT_VECTORTYPE                     0x18014
#define HID_DONE                                0x18015
#define HID_EXAMPLE_TEXT                        0x18016
#define HID_EDITITEM                            0x18017
#define HID_PLAYER_PLAY                         0x18018
#define HID_INSERT_NEXTITEM                     0x18019
#define HID_PLAYER_PAUSE                        0x1801A
#define HID_INSERT_SUBITEM                      0x1801B
#define HID_PLAYER_STOP                         0x1801C
#define HID_PLAYER_FASTFORWARD                  0x1801D
#define HID_PLAYER_SKIP                         0x1801E
#define HID_FILE_REPLAYLOG                      0x1801F
#define HID_FILE_EDITEXAMPLE                    0x18020
#define HID_FILE_VIEWEXAMPLE                    0x18021
#define HID_FILE_OPENPROBLEM                    0x18022
#define HID_VIEW_PLAYCONTROL                    0x18023
#define HID_HELP_WHATSWRONG                     0x18024
#define HID_VIEW_CACLULATOR                     0x18025
#define HID_CALCULATOR                          0x18026
#define HID_GROUP                               0x18027
#define HID_EDIT_UNGROUP                        0x18028
#define HID_UNGROUP                             0x18029
#define HID_PLAN_ADDNEWGOAL                     0x1802A
#define HID_PLAN_EDITTHISITEM                   0x1802B
#define HID_PLAN_INSERTSUBITEM                  0x1802C
#define HID_PLAN_DELETE                         0x1802D
#define HID_VIEW_GRID                           0x1802E
#define HID_VIEW_ALIGNTOGRID                    0x1802F
#define HID_ALIGNTOGRID                         0x18030
#define HID_WINDOW_MINIMIZERIGHT                0x18031
#define HID_PLAN_HELP_WHATSWRONG                0x18032
#define HID_GET_PROC_HELP                       0x18033
#define HID_NEW_VARIABLE                        0x18034
#define HID_VARIABLE_LIST                       0x18035
#define HID_POPUP_EXPLAIN                       0x18036
#define HID_PLAN_TEMPLATE                       0x18037
#define HID_PLAN_SUBMIT                         0x18038
#define HID_DIAGRAM_TOGGLEGROUP                 0x18039
#define HID_CHOICE_ITEM                         0x1803A
#define HID_PLAN_DONE                           0x1803B
#define HID_EDIT_AUTHORPROPERTIES               0x1803C
#define HID_AUTHORPROPS                         0x1803D
#define HID_HELP_SHOWLESSON                     0x1803E
#define HID_SHOWLESSON                          0x1803F
#define HID_MC_QUESTION                         0x18040
#define HID_FILE_SHOWRULEDLG                    0x18041
#define HID_SHOWRULEDLG                         0x18042
#define HID_PHYS_REVIEW_EQN                     0x18044
#define HID_VIEW_FONT                           0x18045
#define HID_2DMOTION                            0x18046
#define HID_POPUP_ADDNEWVARIABLE                0x18047
#define HID_MODIFY_VARIABLE                     0x18048
#define HID_DELETE_VARIABLE                     0x18049
#define HID_VARIABLE_WHATSWRONG                 0x1804A
#define HID_VARIABLE_NEW                        0x1804B
#define HID_VARIABLE_MODIFY                     0x1804C
#define HID_HELP_DRAWFORCE                      0x18084
#define HID_HELP_DRAWVELOCITY                   0x18085
#define HID_HELP_DRAWACCELERATION               0x18086
#define HID_HELP_DRAWBODY                       0x18087
#define HID_TRAINBODY                           0x18088
#define HID_TRAINFORCE                          0x18089
#define HID_TRAINVELOCITY                       0x1808A
#define HID_TRAINACCELERATION                   0x1808B
#define HID_TBODY_TOOL                          0x1808C
#define HID_TBODY_DLG                           0x1808D
#define HID_TBODY_LABEL                         0x1808E
#define HID_TBODY_BODY                          0x1808F
#define HID_TBODY_TIME                          0x18090
#define HID_TFORCE_TOOL                         0x18097
#define HID_TFORCE_BDOWN                        0x18098
#define HID_TFORCE_DLG                          0x18099
#define HID_TFORCE_TIME                         0x1809A
#define HID_TFORCE_LABEL                        0x1809B
#define HID_TFORCE_BODY                         0x1809C
#define HID_TFORCE_DIRECTION                    0x1809D
#define HID_TFORCE_TYPE                         0x1809E
#define HID_TFORCE_AGENT                        0x1809F
#define HID_TVELOCITY_TOOL                      0x180A1
#define HID_TVELOCITY_BDOWN                     0x180A2
#define HID_TVELOCITY_DLG                       0x180A3
#define HID_TVELOCITY_TIME                      0x180A4
#define HID_TVELOCITY_LABEL                     0x180A5
#define HID_TVELOCITY_DIRECTION                 0x180A7
#define HID_TVELOCITY_BODY                      0x180AA
#define HID_TACCELERATION_TOOL                  0x180AB
#define HID_TACCELERATION_BDOWN                 0x180AC
#define HID_TACCELERATION_DLG                   0x180AD
#define HID_TACCELERATION_TIME                  0x180AE
#define HID_TACCELERATION_LABEL                 0x180AF
#define HID_TACCELERATION_DIRECTION             0x180B1
#define HID_TACCELERATION_BODY                  0x180B4
#define HID_TRAINRULER                          0x180B5
#define HID_TRULER_TOOL                         0x180B6
#define HID_TRULER_BDOWN                        0x180B7
#define HID_TRULER_DLG                          0x180B8
#define HID_TMOTACC_TIME                        0x180B9
#define HID_HELP_DRAWMOTIONBODY                 0x180BB
#define HID_HELP_DRAWPOSITION                   0x180BC
#define HID_TRAINPOSITION                       0x180BD
#define HID_TPOSITION_TOOL                      0x180BE
#define HID_HELP_DRAWMOTVEL                     0x180BF
#define HID_TRAINMOTVEL                         0x180C0
#define HID_TMOTVEL_TOOL                        0x180C1
#define HID_TMOTVEL_BDOWN                       0x180C2
#define HID_HELP_DRAWMOTACC                     0x180C3
#define HID_TRAINMOTACC                         0x180C4
#define HID_TMOTACC_TOOL                        0x180C5
#define HID_TMOTACC_BDOWN                       0x180C6
#define HID_TRULER_BODY                         0x180C9
#define HID_TRULER_DTIME                        0x180CA
#define HID_TRULER_MTIME                        0x180CB
#define HID_TRULER_INTERVAL                     0x180CC
#define HID_TRULER_UNITS                        0x180CD
#define HID_DRAWMOTIONBODY                      0x180CE
#define HID_DRAWPOSITION                        0x180CF
#define HID_DRAWMOTVEL                          0x180D0
#define HID_DRAWMOTACC                          0x180D1
#define HID_ENDMOTIONDGRM                       0x180D2
#define HID_FILE_SHOWDEMO                       0x180D3
#define HID_VIEW_PTR                            0x180D4
#define HID_VIEW_PTR_DLG                        0x180D5
#define HID_ADDSYMBOL                           0x180D6
#define HID_HINTBTN_FIRST                       0x180DA
#define HID_HINTBTN_HINT                        0x180DA
#define HID_FOLLOWUP_HOW                        0x180DB
#define HID_FOLLOWUP_EXPLAIN                    0x180DC
#define HID_FOLLOWUP_WHY                        0x180DD
#define HID_HINTBTN_WHATSWRONG                  0x180DE
#define HID_HINTBTN_HIDE                        0x180DF
#define HID_HINTBTN_LAST                        0x180DF
#define HID_VIEW_HIDE_HINT                      0x180E0
#define HID_HYPERTEXT                           0x18115
#define HID_PLAYER_REPLAY_HELP                  0x18116
#define HID_PLAYER_QUIT_DEMO                    0x18117
#define HID_HELP_DRAWDISPLACEMENT               0x18119
#define HID_TRAINDISPLACEMENT                   0x1811A
#define HID_PLAYER_GOTO                         0x1811A
#define HID_TDISPLACEMENT_TOOL                  0x1811B
#define HID_TDISPLACEMENT_BDOWN                 0x1811C
#define HID_TDISPLACEMENT_DLG                   0x1811D
#define HID_TDISPLACEMENT_TIME                  0x1811E
#define HID_NEWTONSFIRST                        0x1811E
#define HID_TDISPLACEMENT_LABEL                 0x1811F
#define HID_NEWTONSSECOND                       0x1811F
#define HID_KINEMATICS                          0x18120
#define HID_TDISPLACEMENT_DIRECTION             0x18121
#define HID_ENERGY                              0x18121
#define HID_WORK                                0x18122
#define HID_TDISPLACEMENT_BODY                  0x18124
#define HID_VARIABLE_ADDFIRST                   0x18126
#define HID_VARIABLE_ADDFORCE                   0x18126
#define HID_VARIABLE_ADDACCELERATION            0x18127
#define HID_VARIABLE_ADDVELOCITY                0x18128
#define HID_VARIABLE_ADDDISPLACEMENT            0x18129
#define HID_VARIABLE_ADDRADIUS                  0x1812A
#define HID_VARIABLE_ADDCOMPRESSION             0x1812B
#define HID_VARIABLE_ADDDISTANCE                0x1812C
#define HID_VARIABLE_ADDDISTTRAV                0x1812D
#define HID_VARIABLE_ADDMASS                    0x1812E
#define HID_VARIABLE_ADDSPEED                   0x1812F
#define HID_VARIABLE_ADDTIME                    0x18130
#define HID_VARIABLE_ADDANGLE                   0x18131
#define HID_VARIABLE_ADDWORK                    0x18132
#define HID_VARIABLE_ADDNRG                     0x18133
#define HID_VARIABLE_ADDSPRINGCONST             0x18134
#define HID_VARIABLE_ADDHEIGHT                  0x18135
#define HID_VARIABLE_ADDANGACCELERATION         0x18136
#define HID_VARIABLE_ADDANGVELOCITY             0x18137
#define HID_VARIABLE_ADDANGDISPLACEMENT         0x18138
#define HID_VARIABLE_ADDLAST                    0x18139
#define HID_TEXTBOOK                            0x18146
#define HID_COMMENT                             0x18147
#define HID_SOUGHT_FIRST                        0x18148
#define HID_SOUGHT_FORCEMAG                     0x18148
#define HID_SOUGHT_ACCMAG                       0x18149
#define HID_SOUGHT_VELMAG                       0x1814A
#define HID_SOUGHT_DISPMAG                      0x1814B
#define HID_SOUGHT_RADIUS                       0x1814C
#define HID_SOUGHT_COMPRESSION                  0x1814D
#define HID_SOUGHT_DISTANCE                     0x1814E
#define HID_SOUGHT_DISTTRAV                     0x1814F
#define HID_SOUGHT_MASS                         0x18150
#define HID_SOUGHT_SPEED                        0x18151
#define HID_SOUGHT_TIME                         0x18152
#define HID_VARIABLE_ENDLIST                    0x18153
#define HID_SOUGHT_FORCEDIR                     0x18153
#define HID_SOUGHT_ACCDIR                       0x18154
#define HID_SOUGHT_VELDIR                       0x18155
#define HID_SOUGHT_DISPDIR                      0x18156
#define HID_SOUGHT_LAST                         0x18156
#define HID_ADDPROP_FIRST                       0x1815A
#define HID_ADDPROP_FORCE                       0x1815A
#define HID_ADDPROP_KINEMATICFIRST              0x1815B
#define HID_ADDPROP_ACCELERATION                0x1815B
#define HID_ADDPROP_VELOCITY                    0x1815C
#define HID_ADDPROP_DISPLACEMENT                0x1815D
#define HID_ADDPROP_TIME                        0x1815E
#define HID_ADDPROP_KINEMATICLAST               0x1815E
#define HID_ADDPROP_MASS                        0x1815F
#define HID_ADDPROP_RADIUS                      0x18160
#define HID_ADDPROP_GRAVACC                     0x18161
#define HID_ADDPROP_COEFFRICTION                0x18162
#define HID_ADDPROP_LAST                        0x18163
#define HID_ADD_HELP_FILE                       0x18164
#define HID_PLAYER_STEP                         0x1816A
#define HID_ADD_OPTION                          0x1816B
#define HID_PROBLEMSET_DELETE                   0x1816C
#define HID_PROBSET_ADD_PROB                    0x1816D
#define HID_PROBSET_ADD_OPT                     0x1816E
#define HID_PROBSET_DELETE_PROB                 0x18170
#define HID_PROBSET_DELETE_OPTION               0x18171
#define HID_PRINCIPLE_ADD                       0x18172
#define HID_PRINCIPLE_DELETE                    0x18173
#define HID_GREEK                               0x1817A
#define HID_SOLVEFOR                            0x1817B
#define HID_FILE_OPENPROBLEMSET                 0x1817C
#define HID_OPEN_PROBLEM                        0x1817D
#define HID_FILE_EDIT_PROBSET                   0x1817E
#define HID_DELETE_SOLUTION                     0x1817E
#define HID_VARIABLE_SOLVEFOR                   0x18180
#define HID_DIALOG_WHATSWRONG                   0x18181
#define HID_PRINCIPLE_CHECK                     0x18182
#define HID_PRINCIPLE_UNCHECK                   0x18183
#define HID_PRINCIPLE_MODIFY                    0x18184
#define HID_POPUP_SOLVEFOR                      0x18186
#define HID_VARIABLE_ADDNEW                     0x18191
#define HID_PROBLEMSET_MOVEUP                   0x18193
#define HID_PROBSET_MOVEUP                      0x18194
#define HID_PROBLEMSET_MOVEDOWN                 0x18195
#define HID_PROBSET_MOVEDOWN                    0x18196
#define HID_TVELOCITY_TYPE                      0x181C6
#define HID_TACCELERATION_TYPE                  0x181D0
#define HID_DRAWTOOL_FIRST                      0x1C350
#define HID_DRAW_VECTOR                         0x1C350
#define HID_DIAGRAM_COORDINATES                 0x1C351
#define HID_SYSTEM                              0x1C352
#define HID_LABEL                               0x1C353
#define HID_ANGLE                               0x1C354
#define HID_SELECT                              0x1C355
#define HID_GUIDE_LINE                          0x1C356
#define HID_RECTANGLE                           0x1C357
#define HID_ROUNDRECT                           0x1C358
#define HID_ELLIPSE                             0x1C359
#define HID_LINE                                0x1C35A
#define HID_ARC                                 0x1C35B
#define HID_ARC2                                0x1C35C
#define HID_POLYGON                             0x1C35D
#define HID_POLYBEZIER                          0x1C35E
#define HID_RULER                               0x1C35F
#define HID_MOTION_BODY                         0x1C360
#define HID_DOC_AREA                            0x1C361
#define HID_LABEL_RADIUS                        0x1C362
#define HID_DRAWTOOL_LAST                       0x1C362
#define HIDM_GREEKLETTER_FIRST                  0x1C452
#define HIDM_ALPHA                              0x1C452
#define HIDM_BETA                               0x1C453
#define HIDM_GAMMA                              0x1C454
#define HIDM_DELTA                              0x1C455
#define HIDM_EPSILON                            0x1C456
#define HIDM_ZETA                               0x1C457
#define HIDM_ETA                                0x1C458
#define HIDM_THETA                              0x1C459
#define HIDM_IOTA                               0x1C45A
#define HIDM_KAPPA                              0x1C45B
#define HIDM_LAMBDA                             0x1C45C
#define HIDM_MU                                 0x1C45D
#define HIDM_NU                                 0x1C45E
#define HIDM_XI                                 0x1C45F
#define HIDM_OMICRON                            0x1C460
#define HIDM_PI                                 0x1C461
#define HIDM_RHO                                0x1C462
#define HIDM_SIGMA                              0x1C463
#define HIDM_TAU                                0x1C464
#define HIDM_UPSILON                            0x1C465
#define HIDM_PHI                                0x1C466
#define HIDM_CHI                                0x1C467
#define HIDM_PSI                                0x1C468
#define HIDM_OMEGA                              0x1C469
#define HIDM_GREEKLETTER_LAST                   0x1C469
#define HID_DIRECTION_FIRST                     0x1C47C
#define HID_VERTICAL                            0x1C47C
#define HID_HORIZONTAL                          0x1C47D
#define HID_VERTANDHORZ                         0x1C47E
#define HID_PARALLEL_FIRST                      0x1C47F
#define HID_OTHER                               0x1C47F
#define HID_TWO_OTHER                           0x1C480
#define HID_PARALLEL_LAST                       0x1C480
#define HID_DIRECTION_LAST                      0x1C481
#define HID_NEXT_FIRST                          0x1C482
#define HID_WEREDONE                            0x1C482
#define HID_CANCELUNKNOWN                       0x1C483
#define HID_SUBSTAGE                            0x1C484
#define HID_NEWSTAGE                            0x1C485
#define HID_NEXT_LAST                           0x1C485
#define HID_FILE_OPENSOLUTION                   0x1E142
#define HID_INDICATOR_ANGLE                     0x1E706
#define HID_VIEW_AUTHORBAR                      0x1E805
#define HID_VIEW_PROBLEMBAR                     0x1E806
#define HID_VIEW_EQBAR                          0x1E807
#define HID_SOLVEFOR_MENU                       0x1EA60
#define HID_SOLVEFOR_FIRST                      0x1EA61
#define HID_SOLVEFOR_LAST                       0x1EC54
 
// Prompts (IDP_*) 
#define HIDP_BUSY                               0x30064
#define HIDP_OLE_INIT_FAILED                    0x30065
#define HIDP_FAILED_TO_CREATE                   0x30066
 
// Resources (IDR_*) 
#define HIDR_FBDTYPE_CNTR_IP                    0x20006
#define HIDR_POPUP_FBDVIEW                      0x20066
#define HIDR_POPUP_EXPLAIN_OLD                  0x2006E
#define HIDR_POPUP_EQVIEW                       0x2006F
#define HIDR_MAINFRAME                          0x20080
#define HIDR_FBDTYPE                            0x20081
#define HIDR_EXAMPLETYPE                        0x20082
#define HIDR_POPUP_EXPLAIN                      0x20083
#define HIDR_PROBSET_TYPE                       0x20084
#define HIDR_PROBSETEDIT_TYPE                   0x20085
#define HIDR_EXEDITTYPE                         0x20086
#define HIDR_AUTHORBAR                          0x20099
#define HIDR_PLAYER                             0x200A9
#define HIDR_PLAYER_CMDS                        0x200A9
#define HIDR_STATUS                             0x200B5
#define HIDR_IMAGE                              0x200C2
#define HIDR_POPUP_PLANVIEW                     0x200C3
#define HIDR_QUALTOOLS                          0x200D8
#define HIDR_QUANTBAR                           0x200DA
#define HIDR_MAINFRAME1                         0x200DB
#define HIDR_ALLTOOLS                           0x200DB
#define HIDR_POPUP_VARVIEW                      0x200EB
#define HIDR_TOOLBAR1                           0x200FF
#define HIDR_GREEK                              0x2010A
#define HIDR_MOTION                             0x20121
#define HIDR_NEXT                               0x20121
#define HIDR_DIRECTIONS                         0x20123
#define HIDR_PLAN                               0x20125
#define HIDR_MAINFRAME_EXP                      0x2012A
#define HIDR_POPUP_SOUGHT                       0x2014D
#define HIDR_POPUP_PROPERTY                     0x2014E
#define HIDR_POPUP_HILEVELVW                    0x20150
#define HIDR_POPUP_PRINCVIEW                    0x20157
#define HIDR_EQBAR                              0x20158
#define HIDR_POPUP_DIALOG                       0x20161
#define HIDR_POPUP_SOLVEFOR                     0x20162
#define HIDR_POPUP_VARVIEW_NRG                  0x20163
#define HIDR_POPUP_LOGEDIT                      0x20164
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_TABVIEW                            0x20065
#define HIDD_HELPFILES_PAGE                     0x20066
#define HIDD_PLAYERBAR                          0x20067
#define HIDD_OLE_PROPPAGE_LARGE                 0x20069
#define HIDD_PLANPAGE                           0x2006A
#define HIDD_VECTOR_FORCE                       0x20085
#define HIDD_VECTOR                             0x20086
#define HIDD_SYSTEM                             0x20087
#define HIDD_LABEL                              0x20089
#define HIDD_AXES                               0x2008A
#define HIDD_HELP_OPTIONS                       0x2008E
#define HIDD_LISTS_PAGE                         0x2008F
#define HIDD_GENERAL_PAGE                       0x20091
#define HIDD_OBJECTS_PAGE                       0x20092
#define HIDD_TIMES_PAGE                         0x20093
#define HIDD_DIRECTIONS_PAGE                    0x20094
#define HIDD_EQ_FORM                            0x20095
#define HIDD_PROP_RECT                          0x2009B
#define HIDD_EXPERIMENT                         0x2009C
#define HIDD_PLAYER                             0x2009C
#define HIDD_VIEW_OPTS                          0x2009E
#define HIDD_FORCE_TYPE                         0x200A4
#define HIDD_EXAMPLE_TEXT                       0x200A7
#define HIDD_REVIEW_BROWSER                     0x200A8
#define HIDD_DONE                               0x200AD
#define HIDD_PLANNER                            0x200B0
#define HIDD_MOTION_DIAGRAM                     0x200B3
#define HIDD_STEP1                              0x200B4
#define HIDD_STEP                               0x200B4
#define HIDD_STEP2                              0x200B5
#define HIDD_LOGIN                              0x200B7
#define HIDD_HINT                               0x200B9
#define HIDD_VARIABLE_LIST                      0x200BA
#define HIDD_VECTOR_MOVE                        0x200BB
#define HIDD_VECTOR_COMP                        0x200BC
#define HIDD_DECLARE_VARIABLE                   0x200BD
#define HIDD_MIDSTEP                            0x200BE
#define HIDD_EXPLAIN_SYSTEM                     0x200C0
#define HIDD_EXPLAIN_BODY                       0x200C1
#define HIDD_CHOICE                             0x200C4
#define HIDD_AREA                               0x200C5
#define HIDD_INSTRUCT                           0x200C7
#define HIDD_WARNING                            0x200C8
#define HIDD_EXPLAIN                            0x200CC
#define HIDD_EX_FORM                            0x200D1
#define HIDD_ANGLE                              0x200D4
#define HIDD_AUTHOR_PROPS                       0x200D7
#define HIDD_TASK_SELECTION                     0x200DD
#define HIDD_CHOICE_GROUP                       0x200DE
#define HIDD_RULE_QUERY                         0x200DF
#define HIDD_UPLOAD                             0x200E1
#define HIDD_EXHINT                             0x200E4
#define HIDD_EXAMPLE_PLAN                       0x200E8
#define HIDD_EXPLAIN_TWO                        0x200ED
#define HIDD_EXPLAIN_FOUR                       0x200EE
#define HIDD_DEMO_UI                            0x200F4
#define HIDD_DEMO_POINTER                       0x200F5
#define HIDD_DIALOG1                            0x200F7
#define HIDD_SYMBOL                             0x200F7
#define HIDD_HINTBAR                            0x200F8
#define HIDD_LABELRADIUS                        0x200FB
#define HIDD_GREEKBAR                           0x200FC
#define HIDD_PTR_MSG                            0x2010D
#define HIDD_FILEOPEN_PIC                       0x20110
#define HIDD_HYPER_TEXT                         0x20111
#define HIDD_HORZ_GREEKBAR                      0x20112
#define HIDD_VARPAGE                            0x20113
#define HIDD_EXPLAIN_LAW                        0x20124
#define HIDD_PROPTYPE                           0x20126
#define HIDD_KINEMATICPROP                      0x20127
#define HIDD_PROPERTY                           0x20127
#define HIDD_VARTYPE                            0x2012B
#define HIDD_COMMENT                            0x20149
#define HIDD_FORMULA                            0x2014A
#define HIDD_POSITIONS_PAGE                     0x20150
#define HIDD_PROBSETEDITVIEW                    0x20151
#define HIDD_VECTOR_DISP                        0x20152
#define HIDD_DRAWOBJ                            0x20154
#define HIDD_PRINCIPLE_FORM                     0x20155
#define HIDD_LAW_APPLICATION                    0x20156
#define HIDD_PROBSET_VIEW                       0x20157
#define HIDD_SOLVEFOR                           0x2015A
#define HIDD_PROBSET_OPTIONS                    0x2015E
#define HIDD_ENERGY                             0x20166
 
// Frame Controls (IDW_*) 
#define HIDW_AUTHORBAR                          0x5E805
#define HIDW_PROBLEMBAR                         0x5E806
#define HIDW_EQBAR                              0x5E807
