//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FBD.rc
//
#define IDR_FBDTYPE_CNTR_IP             6
#define IDD_ABOUTBOX                    100
#define IDP_BUSY                        100
#define IDP_OLE_INIT_FAILED             101
#define IDD_TABVIEW                     101
#define IDR_POPUP_FBDVIEW               102
#define IDC_WEIGHT                      102
#define IDP_FAILED_TO_CREATE            102
#define IDD_HELPFILES_PAGE              102
#define IDC_NOFILL                      103
#define IDD_PLAYERBAR                   103
#define IDS_LABEL_NOTUNIQUE             103
#define IDC_SPIN1                       104
#define IDS_AUTODEF_OBJ                 104
#define IDC_DRAWDISPLACEMENT            104
#define IDS_SAMEDEF_VAR                 104
#define ID_INDICATOR_TIME               105
#define IDD_OLE_PROPPAGE_LARGE          105
#define IDS_REPLACE_BADVAR              106
#define IDD_PLANPAGE                    106
#define IDD_STATEMENT_PAGE              106
#define IDS_REDEFINE_OBJ                107
#define ID_EXPLAIN                      108
#define IDS_SAMEDEF_OBJ                 108
#define CG_IDS_SOCKETS_INIT_FAILED      109
#define IDR_POPUP_EXPLAIN_OLD           110
#define IDS_REDEFINE_VAR                110
#define IDR_POPUP_EQVIEW                111
#define IDS_PLAN_DIRECT                 111
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    112
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 113
#define IDS_RULE_DIRECT                 114
#define IDS_SELAXIS                     115
#define IDS_RULE_FORM                   116
#define IDB_SPLASH                      117
#define IDS_PLAN_FORM                   117
#define IDS_RULE_HEAD                   118
#define IDS_ASK_SAVECOPY                119
#define IDS_PROP_EXISTS                 120
#define IDS_ITEMSYSTEM                  121
#define IDS_ITEMSOUGHT                  122
#define IDS_ITEMMOTION                  123
#define IDS_ITEMLAW                     124
#define IDS_ITEMSYSPROP                 125
#define IDS_ITEMDIRECTION               126
#define IDS_ITEMCHKSOLV                 127
#define IDR_MAINFRAME                   128
#define IDR_FBDTYPE                     129
#define IDR_EXAMPLETYPE                 130
#define IDR_POPUP_EXPLAIN               131
#define IDS_ITEMUNKNOWN                 131
#define IDR_PROBSET_TYPE                132
#define IDR_PROBSETEDIT_TYPE            133
#define IDD_VECTOR_FORCE                133
#define IDR_EXEDITTYPE                  134
#define IDD_VECTOR                      134
#define IDD_SYSTEM                      135
#define IDS_LABEL_PREDEFINED            135
#define IDR_TASK_TYPE                   136
#define IDD_LABEL                       137
#define IDS_PROPERTIES                  137
#define IDD_AXES                        138
#define IDD_HELP_OPTIONS                142
#define IDD_LISTS_PAGE                  143
#define IDD_GENERAL_PAGE                145
#define IDD_OBJECTS_PAGE                146
#define IDD_TIMES_PAGE                  147
#define IDD_DIRECTIONS_PAGE             148
#define IDD_BRANCHES_PAGE               148
#define IDD_EQ_FORM                     149
#define IDR_AUTHORBAR                   153
#define IDD_PROP_RECT                   155
#define IDD_EXPERIMENT                  156
#define IDD_PLAYER                      156
#define IDD_VIEW_OPTS                   158
#define IDD_FORCE_TYPE                  164
#define IDD_EXAMPLE_TEXT                167
#define IDD_REVIEW_BROWSER              168
#define IDR_PLAYER                      169
#define IDR_PLAYER_CMDS                 169
#define IDI_GOSIGN                      170
#define IDD_DONE                        173
#define IDD_PLANNER                     176
#define IDD_MOTION_DIAGRAM              179
#define IDD_STEP1                       180
#define IDD_STEP                        180
#define IDD_STEP2                       181
#define IDR_STATUS                      181
#define IDD_LOGIN                       183
#define IDD_HINT                        185
#define IDD_VARIABLE_LIST               186
#define IDD_VECTOR_MOVE                 187
#define IDD_VECTOR_COMP                 188
#define IDD_DECLARE_VARIABLE            189
#define IDD_MIDSTEP                     190
#define IDD_EXPLAIN_SYSTEM              192
#define IDD_EXPLAIN_BODY                193
#define IDR_IMAGE                       194
#define IDR_POPUP_PLANVIEW              195
#define IDD_CHOICE                      196
#define IDD_AREA                        197
#define IDD_INSTRUCT                    199
#define IDD_WARNING                     200
#define IDD_EXPLAIN                     204
#define IDD_EX_FORM                     209
#define IDD_ANGLE                       212
#define IDD_AUTHOR_PROPS                215
#define IDR_QUALTOOLS                   216
#define IDR_QUANTBAR                    218
#define IDR_MAINFRAME1                  219
#define IDR_ALLTOOLS                    219
#define IDI_ANGLE                       220
#define IDD_TASK_SELECTION              221
#define IDD_CHOICE_GROUP                222
#define IDD_RULE_QUERY                  223
#define IDD_UPLOAD                      225
#define IDD_EXHINT                      228
#define IDD_EXAMPLE_PLAN                232
#define IDR_POPUP_VARVIEW               235
#define IDD_EXPLAIN_TWO                 237
#define IDD_EXPLAIN_FOUR                238
#define IDD_DEMO_UI                     244
#define IDD_DEMO_POINTER                245
#define IDI_POINT_UPLEFT                246
#define IDD_DIALOG1                     247
#define IDD_SYMBOL                      247
#define IDB_QMARK                       248
#define IDD_HINTBAR                     248
#define IDD_LABELRADIUS                 251
#define IDB_GREEK                       252
#define IDD_GREEKBAR                    252
#define IDR_TOOLBAR1                    255
#define IDB_BITMAP1                     257
#define IDR_GREEK                       266
#define IDD_PTR_MSG                     269
#define IDC_LINK                        270
#define IDD_FILEOPEN_PIC                272
#define IDD_HYPER_TEXT                  273
#define IDD_HORZ_GREEKBAR               274
#define IDC_ANGSIZE                     275
#define IDD_VARPAGE                     275
#define IDC_DRAWBODY                    276
#define IDC_DRAWAXES                    277
#define IDC_DRAWFORCE                   278
#define IDC_DRAWVELOCITY                280
#define IDC_DRAWACCELERATION            281
#define IDC_DRAWCOMPONENT               282
#define IDC_DRAWANGLE                   283
#define IDC_DRAWRADIUS                  284
#define IDC_ZACCEL_INTO                 285
#define IDC_ZVEL_INTO                   286
#define IDC_ZACCEL_OUTOF                287
#define IDC_ZVEL_OUTOF                  288
#define IDR_MOTION                      289
#define IDR_NEXT                        289
#define IDC_ZDISP_INTO                  289
#define IDC_ZDISP_OUTOF                 290
#define IDR_DIRECTIONS                  291
#define IDC_DRAWMOMENTUM                291
#define IDD_EXPLAIN_LAW                 292
#define IDC_ZMOM_INTO                   292
#define IDR_PLAN                        293
#define IDC_ZMOM_OUTOF                  293
#define IDD_PROPTYPE                    294
#define IDC_ZTOR_INTO                   294
#define IDD_KINEMATICPROP               295
#define IDD_PROPERTY                    295
#define IDC_ZTOR_OUTOF                  295
#define IDC_DRAWRELPOS                  296
#define IDC_DRAWTORQUE                  297
#define IDR_MAINFRAME_EXP               298
#define IDD_VARTYPE                     299
#define IDS_FIRST_TIP                   300
#define IDS_ALPHA                       300
#define IDS_BETA                        301
#define IDS_GAMMA                       302
#define IDS_DELTA                       303
#define IDS_EPSILON                     304
#define IDS_ZETA                        305
#define IDS_ETA                         306
#define IDS_THETA                       307
#define IDS_IOTA                        308
#define IDS_KAPPA                       309
#define IDS_LAMBDA                      310
#define IDS_MU                          311
#define IDS_NU                          312
#define IDS_XI                          313
#define IDS_OMICRON                     314
#define IDS_PI                          315
#define IDS_RHO                         316
#define IDS_SIGMA                       317
#define IDS_TAU                         318
#define IDS_UPSILON                     319
#define IDS_PHI                         320
#define IDS_CHI                         321
#define IDS_PSI                         322
#define IDS_OMEGA                       323
#define IDS_NEWTONSFIRST                324
#define IDS_NEWTONSSECOND               325
#define IDS_KINEMATICS                  326
#define IDS_ENERGY                      327
#define IDS_NETWORK                     328
#define IDD_COMMENT                     329
#define IDD_FORMULA                     330
#define IDR_POPUP_SOUGHT                333
#define IDR_POPUP_PROPERTY              334
#define IDD_POSITIONS_PAGE              336
#define IDR_POPUP_HILEVELVW             336
#define IDD_PROBSETEDITVIEW             337
#define IDD_VECTOR_DISP                 338
#define IDD_DRAWOBJ                     340
#define IDD_PRINCIPLE_FORM              341
#define IDD_LAW_APPLICATION             342
#define IDR_POPUP_PRINCVIEW             343
#define IDD_PROBSET_VIEW                343
#define IDR_EQBAR                       344
#define IDR_ROTKINTOOLS                 345
#define IDD_SOLVEFOR                    346
#define IDB_GREEKBTN                    349
#define IDD_PROBSET_OPTIONS             350
#define IDB_CHECKS                      352
#define IDR_POPUP_DIALOG                353
#define IDR_POPUP_SOLVEFOR              354
#define IDR_POPUP_VARVIEW_NRG           355
#define IDR_POPUP_LOGEDIT               356
#define IDR_POPUP_ZDIR                  356
#define IDD_ENERGY                      358
#define IDB_ATLAS_SPLASH                363
#define IDD_TRACE                       364
#define IDD_TORQUE                      365
#define IDD_VECTOR_POS                  368
#define IDD_WORK                        371
#define IDD_PSM                         372
#define IDD_TRANSFER                    373
#define IDD_VOLTAGE_OLD                 374
#define IDD_CURRENT_EXP                 376
#define IDD_RESISTANCE                  377
#define IDD_DIALOG2                     378
#define IDD_CURRENT                     379
#define IDD_VOLTAGE                     380
#define IDD_VECTOR_RELVEL               381
#define IDB_ONRLOGO                     383
#define IDD_FIELD                       384
#define IDR_EMTOOLS                     386
#define IDR_SPLASH_JPG                  387
#define IDC_DRAWEFIELD                  388
#define IDC_DRAWBFIELD                  389
#define IDR_ONR_LOGO                    390
#define IDD_VIDEO                       390
#define IDD_OLIVIEW                     391
#define IDD_VECTOR_IMPULSE              392
#define IDD_PROBABILITY                 394
#define IDC_SINGLE_BODY                 1000
#define IDC_STATUS_MSG                  1000
#define IDC_MULTIPLE_BODIES             1001
#define IDC_WEB_BROWSER                 1002
#define IDC_BACK                        1004
#define IDC_FORWARD                     1005
#define IDC_DIRECTION_SPIN              1006
#define IDC_FORCE                       1007
#define IDC_VELOCITY                    1008
#define IDC_ACCELERATION                1009
#define IDC_COMPONENT                   1010
#define IDC_LABEL_TEXT                  1012
#define IDC_COMP_DIRECTION              1012
#define IDC_WAIT_FEEDBACK               1014
#define IDC_FEEDBACK_ASYNC              1015
#define IDC_X_AXIS                      1016
#define IDC_Y_AXIS                      1017
#define IDC_CHECK_EQUATIONS             1018
#define IDC_COMPONENT_OF                1019
#define IDC_CHECK_DIAGRAM               1020
#define IDC_SYSTEM_NAME                 1030
#define IDC_MULTIPLE_BODY_LIST          1031
#define IDC_TIME_TEXT                   1032
#define IDC_VECTOR_NAME_TEXT            1033
#define IDC_BODY_TEXT                   1034
#define IDC_ORIENTATION_TEXT            1035
#define IDC_FORCE_TYPE                  1036
#define IDC_BODY_TEXT2                  1036
#define IDC_AGENT                       1037
#define IDC_AVBODY_TEXT                 1038
#define IDC_SYSTEM_LIST                 1053
#define IDC_X_LABEL                     1054
#define IDC_Y_LABEL                     1055
#define IDC_DIRECTION_TEXT              1056
#define IDC_LIST_AREA                   1057
#define IDC_LIST_CHOICE                 1058
#define IDC_ADD_BUTTON                  1059
#define IDC_DELETE_BUTTON               1060
#define IDC_ARG_TEXT                    1061
#define IDC_PROBLEM_TYPE                1062
#define IDC_EXAMPLE_BUTTON              1063
#define IDC_QUALITATIVE_BUTTON          1064
#define IDC_PROBLEM_NAME                1065
#define IDC_OBJECT_TEXT                 1066
#define IDC_EARTH_TEXT                  1067
#define IDC_TIMES_TEXT                  1068
#define IDC_DIRECTIONS_TEXT             1069
#define IDC_BRANCHES_TEXT               1069
#define IDC_BODY_LIST                   1070
#define IDC_LABEL_BODY                  1071
#define IDC_MULTIPLE_INSTRUCTIONS       1073
#define IDC_VISIBLE                     1074
#define IDC_MASK                        1075
#define IDC_PEN_STYLE                   1076
#define IDC_PEN_DOTTED                  1077
#define IDC_PEN_DASHED                  1078
#define IDC_LOGFILE_NAME                1079
#define IDC_MESSAGE                     1080
#define IDC_PLAY                        1081
#define IDC_MESSAGE2                    1081
#define IDC_STOP                        1082
#define IDC_FAST_FORWARD                1083
#define IDC_MASKMODE                    1084
#define IDC_LIGHTEN                     1085
#define IDC_GREYLEVEL                   1086
#define IDC_TIME                        1087
#define IDC_TASK_TEXT                   1090
#define IDC_EDIT_ITEM                   1091
#define IDC_LOGTIME_TEXT                1092
#define IDC_MULTIPLE_INSTRUCTIONS2      1093
#define IDC_RESET                       1094
#define IDC_CONTINUE                    1096
#define IDC_BTN_WHY                     1097
#define IDC_ADD                         1098
#define IDC_FILL_COLOR                  1099
#define IDC_BOX_COLOR                   1100
#define IDC_CHOOSE_FONT                 1101
#define IDC_SUBMIT                      1102
#define IDC_CHOICE_ADD                  1103
#define IDC_EXTEXT_ID                   1114
#define IDC_LIST1                       1115
#define IDC_PROMPT                      1116
#define IDC_EXFLAGS_LABEL               1117
#define IDC_MOTION_BODY_LIST            1119
#define stc32                           0x045f
#define IDC_DEFAULT_TIMES               1120
#define IDC_STATIC_TEXT                 1121
#define IDC_MEASURED_TIMES              1121
#define IDC_TIME_INTERVAL               1122
#define IDC_TIME_UNITS                  1123
#define IDC_TIME_LABEL                  1124
#define IDC_EDIT_USER_TEXT              1125
#define IDC_OBJECT_LIST                 1126
#define IDC_LOGNAME                     1127
#define IDC_TIME_LIST                   1128
#define IDC_AGENT_LIST                  1129
#define IDC_HINT_TEXT                   1129
#define IDC_VALUE_LIST                  1130
#define IDC_EXPLAIN_MORE                1130
#define IDC_ON_OF_IN                    1131
#define IDC_BTN_HOW                     1131
#define IDC_DUETO                       1132
#define IDC_DURING_AT                   1133
#define IDC_MODIFY                      1133
#define IDC_MIDLIST                     1134
#define IDC_DELETE                      1134
#define IDC_GOAL                        1135
#define IDC_VARIABLE                    1135
#define IDC_DECLARATION                 1136
#define IDC_DONE                        1137
#define IDC_LINE_COLOR                  1137
#define IDC_OBJECT                      1138
#define IDC_EDIT1                       1139
#define IDC_BEGIN_GROUP                 1140
#define IDC_CHOSEN                      1141
#define IDC_CORRECT_CHOICE              1142
#define IDC_BORDER                      1143
#define IDC_AREA_CHOICE                 1144
#define IDC_HIGHLIGHT_BOX               1145
#define IDC_TEMPLATE                    1146
#define IDC_PLAN_DONE                   1147
#define IDC_TEXT                        1148
#define IDC_DIRECTION                   1149
#define IDC_RULETREE                    1150
#define IDC_RULEINDEX                   1151
#define IDC_RADIUS                      1152
#define IDC_PROBLEM_OBJ                 1153
#define IDC_ITEM_ID                     1154
#define IDC_ANGLE_NAME                  1155
#define IDC_LINKID2                     1155
#define IDC_THEN                        1156
#define IDC_LINKID1                     1156
#define IDC_DEGREES                     1157
#define IDC_IF                          1158
#define IDC_AND1                        1159
#define IDC_AND2                        1160
#define IDC_EXERTED_BY                  1161
#define IDC_COMBO1                      1162
#define IDC_COMBO2                      1163
#define IDC_COMBO3                      1164
#define IDC_COMBO4                      1165
#define IDC_COMBO5                      1166
#define IDC_TOP_MARKER                  1169
#define IDC_CLOSE                       1170
#define IDC_BUTTON3                     1172
#define IDC_NOTHANKS                    1172
#define ID_UPDATE_HASH                  1172
#define ID_UPDATE_GRPH                  1173
#define IDC_WHATSWRONG                  1174
#define IDC_CHOICE_REMOVE               1175
#define IDC_EDIT_CORRECT                1177
#define IDC_CHOICE_EDIT                 1180
#define IDC_CHOICE_LIST                 1181
#define IDC_CHOICE_QUESTION             1182
#define IDC_MCQ_ID                      1183
#define IDC_TEXT_INSTRUCTIONS           1184
#define IDC_CHOICE_UP                   1185
#define IDC_CHOICE_DOWN                 1186
#define IDC_EXP_MENU                    1188
#define IDC_Q1_CHOICES                  1188
#define IDC_DESCR_TEXT                  1189
#define IDC_TEXT_Q1                     1189
#define IDC_BTN_Q1_ENTER                1190
#define IDC_Q2_CHOICES                  1191
#define IDC_TEXT_Q2                     1192
#define IDC_BTN_Q2_ENTER                1193
#define IDC_TEXT_RESULT                 1194
#define IDC_DONTKNOW                    1195
#define IDC_TEXT_RESULT2                1196
#define IDC_PASSWORD                    1196
#define IDC_SERVER                      1198
#define IDC_ENTER_DATA                  1199
#define IDC_USERNAME                    1200
#define IDC_MESSAGE_TEXT                1202
#define IDC_CLARIFY                     1210
#define IDC_OKCLARIFY                   1212
#define IDC_SCALETOFIT                  1213
#define IDC_LABEL_EDIT                  1214
#define IDC_PICTURE                     1215
#define IDC_PLANTREE                    1216
#define IDC_DIRECT                      1219
#define IDC_HEADING                     1220
#define IDC_BUTTON1                     1223
#define IDC_SELECT_LOGFILE              1223
#define ID_YES                          1223
#define IDC_ALPHA1                      1223
#define IDC_NEWPRINCIPLE_BTN            1223
#define IDC_PSM_HELP                    1223
#define IDC_BROWSE                      1223
#define IDC_PROB_BTN_FIRST              1223
#define IDC_BTN_TILDE                   1223
#define IDC_DELETE_PRINCIPLE            1224
#define IDC_BUTTON2                     1224
#define IDC_BTN_AND                     1224
#define IDC_BTN_OR                      1225
#define IDC_LDEGREES                    1225
#define IDC_BUTTON4                     1225
#define ID_UPDATE_SVARS                 1225
#define IDC_BTN_LPAREN                  1226
#define IDC_LANGLE_NAME                 1226
#define IDC_BUTTON5                     1226
#define ID_UPDATE_ALL                   1226
#define IDC_BTN_RPAREN                  1227
#define IDC_LRADIUS                     1227
#define IDC_BUTTON6                     1227
#define IDC_BTN_A                       1228
#define IDC_LSYSTEM_NAME                1228
#define IDC_BUTTON7                     1228
#define IDC_BTN_B                       1229
#define IDC_LANGLE                      1229
#define IDC_BUTTON8                     1229
#define IDC_BTN_C                       1230
#define IDC_ANGLE                       1230
#define IDC_BUTTON9                     1230
#define IDC_BTN_D                       1231
#define IDC_LVECTOR_NAME_TEXT           1231
#define IDC_BTN_GIVEN                   1232
#define IDC_PROB_BTN_LAST               1232
#define IDC_L2ANGLE                     1232
#define IDC_LFORCE_TYPE                 1233
#define IDC_LAGENT                      1234
#define IDC_LCOMPONENT_OF               1235
#define IDC_LCOMP_DIRECTION             1236
#define IDC_LMOTION_BODY_LIST           1237
#define IDC_LIST_LABEL                  1238
#define IDC_LABEL_AVBODY                1240
#define IDC_INTRO                       1243
#define IDC_XCOMP                       1245
#define IDC_COMP                        1245
#define IDC_YCOMP                       1246
#define IDC_DEMO_MSG                    1250
#define IDC_DEMO_SLIDER                 1251
#define IDC_PTR_ICON                    1252
#define IDC_POINTER_TEXT                1253
#define IDC_BROWSER_TYPE                1253
#define ID_HINTBAR_HIDE                 1254
#define IDC_RICHEDIT1                   1255
#define IDC_BODIES                      1258
#define IDC_LABELRADIUS                 1260
#define ID_INSERT                       1261
#define IDC_ALPHA2                      1262
#define IDC_ALPHA3                      1263
#define IDC_GREEK                       1265
#define IDC_DEF_TEXT                    1267
#define IDC_LINKBTN                     1268
#define IDC_DEFBTN                      1269
#define IDC_LINKTEXT                    1270
#define IDC_DEFTEXT                     1271
#define IDC_HYPERTEXT                   1272
#define IDC_PREVIEW_STATIC              1273
#define IDC_CUSTOM1                     1277
#define IDC_CUSTOM_LABEL                1277
#define IDC_EVENT                       1278
#define IDC_GREEKBTN                    1279
#define IDC_FILE_PREVIEW                1281
#define IDC_PLACEHOLDER                 1282
#define IDC_TABVIEW                     1283
#define IDC_TXT                         1284
#define IDC_FIND                        1285
#define IDC_INCLUDEPLAN                 1286
#define IDC_KBTYPE                      1287
#define IDC_RADIO2                      1288
#define IDC_EXPLAINLAW                  1289
#define IDC_RADIO5                      1289
#define IDC_EXPLAIN_LAW                 1289
#define IDC_RADIO8                      1290
#define IDC_GOTO_HOURS                  1291
#define IDC_RADIO12                     1291
#define IDC_GOTO_MINUTES                1292
#define IDC_RADIO1                      1292
#define IDC_GOTO_SECONDS                1293
#define IDC_RADIO3                      1293
#define IDC_PLAYER_SLIDER               1294
#define IDC_VALUE                       1294
#define IDC_RADIO4                      1294
#define IDC_RADIO6                      1295
#define IDC_BODY                        1296
#define IDC_RADIO7                      1296
#define IDC_PROPERTY                    1297
#define IDC_RADIO9                      1297
#define IDC_PREP1                       1298
#define IDC_PREP2                       1299
#define IDC_STATIC_VALUE                1301
#define IDC_FORCETYPE                   1302
#define IDC_FORCEAGENT                  1303
#define IDC_STATIC_TIME                 1304
#define IDC_STATIC_DUETO                1305
#define IDC_STATIC_BODY                 1306
#define IDC_SCROLLBAR1                  1307
#define IDC_TXT0                        1308
#define ID_CALCULATE                    1309
#define IDC_COMMENT_TEXT                1310
#define IDC_FORMULA                     1311
#define IDC_DEF                         1313
#define IDC_RADIO10                     1314
#define IDC_RADIO11                     1315
#define IDC_RADNAME_TEXT                1316
#define IDC_LRAD_TEXT                   1317
#define IDC_LREV_TEXT                   1318
#define IDC_POSITIONS_TEXT              1319
#define IDC_POS1                        1320
#define IDC_POS2                        1321
#define IDC_MOVEMENT_TYPE               1322
#define IDC_GRPH_INFO                   1323
#define IDC_HASH_INFO                   1324
#define IDC_SVARS_INFO                  1325
#define IDC_GRPH_SRC_INFO               1326
#define IDC_HASH_SRC_INFO               1327
#define IDC_SVARS_SRC_INFO              1328
#define IDC_PDATA_DIR                   1330
#define IDC_VERSION                     1332
#define IDC_NETBTN                      1333
#define IDC_FORCEBTN                    1334
#define IDC_STC_GROUP                   1335
#define IDC_BOX_TIMEDIR                 1336
#define IDC_PRINCIPLES_LIST             1337
#define IDC_BOX_TYPE                    1338
#define IDC_STC_TYPE                    1339
#define IDC_PRINCIPLE                   1340
#define IDC_BOX_TIME                    1341
#define IDC_BOX_2                       1342
#define IDC_BOX_LABEL                   1343
#define IDC_OPTION_LIST                 1344
#define IDC_PROBLEM_LIST                1345
#define IDC_NEWOPT_NAME                 1346
#define IDC_NEWOPT_VALUE                1347
#define IDC_HELPCALLBTN                 1348
#define IDC_VARIABLES                   1349
#define IDC_SIDE1                       1351
#define IDC_SIDE2                       1352
#define IDC_HELP_AVAILABLE              1353
#define IDC_FBD_REQUIRED                1354
#define IDC_COMPLETION_TEST             1355
#define IDC_FIXED_ORDER                 1356
#define IDC_VARIABLE_EQS                1357
#define IDC_EQ_TOOL                     1358
#define IDC_MUST_CORRECT                1359
#define IDC_ALGEBRA_WND                 1360
#define IDC_PRINCIPLE_WND               1361
#define IDC_VAR_STYLE_TIPS              1362
#define IDC_SCAFFOLD_GROUP              1363
#define IDC_CURRIC_GROUP                1364
#define IDC_OPT_VALUE                   1365
#define IDC_STC_SELECTED_OPT            1366
#define IDC_SCAFFOLD_COACHED            1367
#define IDC_SCAFFOLD_SOLO               1368
#define IDC_SCAFFOLD_INTRO              1369
#define IDC_ASSESSOR                    1370
#define IDC_PROBCONCEPT_LIST            1373
#define IDC_AGENT_LABEL                 1374
#define IDC_LVARIABLE_NAME              1375
#define IDC_VARIABLE_NAME               1376
#define IDC_NRGBODY                     1377
#define IDC_LABEL_NRGBODY               1378
#define IDC_NRG_AGENT                   1379
#define IDC_NRG_TYPE                    1380
#define IDC_ANGULAR                     1386
#define IDC_ZDIR                        1387
#define IDC_STC_DIRECTION               1388
#define IDC_PSM_TREE                    1389
#define IDC_PE_LABEL                    1390
#define IDC_TRANSFER                    1392
#define IDC_POINT1                      1394
#define IDC_POINT2                      1395
#define IDC_VOLTAGE_TYPE                1396
#define IDC_VOLTAGE_TYPE2               1397
#define IDC_COMPO                       1402
#define IDC_CURRENT_THRU                1403
#define IDC_CURRENT_IN                  1404
#define IDC_CURRENT_AT                  1405
#define IDC_POINT                       1406
#define IDC_BRANCH                      1407
#define IDC_INSTRUCTIONS                1408
#define IDC_TEXT_STATEMENT              1409
#define IDC_TEXT_FILENAME               1410
#define IDC_ACROSS_LABEL                1411
#define IDC_ANDES_URL                   1412
#define IDC_ANDES_EMAIL                 1413
#define IDC_STATUS                      1414
#define IDC_TASK_NAME                   1415
#define IDC_PROB_TEXT                   1416
#define IDC_GIVEN_VALUE                 1417
#define IDC_CHECK_UNKNOWN               1418
#define IDC_STATIC_OR                   1420
#define IDC_GIVEN_BOX                   1421
#define IDC_STATIC_EQUALS               1422
#define IDC_EQ1                         4000
#define IDC_EQ2                         4001
#define IDI_WINHELP                     4001
#define IDC_EQ3                         4002
#define IDC_EQ4                         4003
#define IDC_EQ5                         4004
#define IDC_EQ6                         4005
#define IDC_EQ7                         4006
#define IDC_EQ8                         4007
#define IDC_EQ9                         4008
#define IDC_EQ10                        4009
#define IDC_EQ12                        4010
#define IDC_EQ11                        4011
#define IDC_EQ13                        4012
#define IDC_EQ14                        4013
#define IDC_EQ15                        4014
#define IDC_EQ16                        4015
#define IDC_EQ17                        4016
#define IDC_EQ18                        4017
#define IDC_EQ19                        4018
#define IDC_EQ20                        4019
#define IDC_EQ21                        4020
#define IDC_EQ22                        4021
#define IDC_EQ23                        4022
#define IDC_EQ24                        4023
#define IDC_EQ25                        4024
#define IDC_EQ26                        4025
#define IDC_EQ27                        4026
#define IDC_EQ28                        4027
#define IDC_EQ29                        4028
#define IDC_EQ30                        4029
#define IDC_EQ31                        4030
#define IDC_EQ32                        4031
#define IDC_EQ33                        4032
#define IDC_EQ34                        4033
#define IDC_EQ35                        4034
#define IDC_EQ36                        4035
#define IDC_EQ37                        4036
#define IDC_EQ38                        4037
#define IDC_EQ39                        4038
#define IDC_EQ40                        4039
#define ID_CANCEL_EDIT                  32768
#define ID_OLD_DRAWVECTOR_FIRST         32769
#define ID_OLD_DRAWVECTOR_FORCE         32769
#define ID_OLD_DRAWVECTOR_VELOCITY      32770
#define ID_OLD_DRAWVECTOR_ACCELERATION  32771
#define ID_OLD_DRAWVECTOR_COMPONENT     32772
#define ID_OLD_DRAWVECTOR_DISPLACEMENT  32773
#define ID_OLD_DRAWVECTOR_MOMENTUM      32774
#define ID_OLD_DRAWVECTOR_RELPOS        32775
#define ID_OLD_DRAWVECTOR_TORQUE        32776
#define ID_OLD_DRAWVECTOR_EFIELD        32777
#define ID_OLD_DRAWVECTOR_BFIELD        32778
#define ID_OLD_DRAWVECTOR_LAST          32778
#define ID_EDIT_DELETE                  32779
#define ID_VARIABLE_DELETE              32780
#define ID_HELP_OPTIONS                 32781
#define ID_EDIT_PROPERTIES              32782
#define ID_DECOMPOSE_VECTOR             32783
#define ID_AUTHORMODE                   32784
#define ID_EDIT_DUPLICATE               32785
#define ID_VIEW_EXPCONTROL              32786
#define ID_VIEW_OPTIONS                 32787
#define ID_EDIT_VECTORTYPE              32788
#define ID_DONE                         32789
#define ID_EXAMPLE_TEXT                 32790
#define ID_EDITITEM                     32791
#define ID_PLAYER_PLAY                  32792
#define ID_INSERT_NEXTITEM              32793
#define ID_PLAYER_PAUSE                 32794
#define ID_INSERT_SUBITEM               32795
#define ID_PLAYER_STOP                  32796
#define ID_PLAYER_FASTFORWARD           32797
#define ID_PLAYER_SKIP                  32798
#define ID_FILE_REPLAYLOG               32799
#define ID_FILE_EDITEXAMPLE             32800
#define ID_FILE_VIEWEXAMPLE             32801
#define ID_FILE_OPENPROBLEM             32802
#define ID_VIEW_PLAYCONTROL             32803
#define ID_HELP_WHATSWRONG              32804
#define ID_VIEW_CACLULATOR              32805
#define ID_CALCULATOR                   32806
#define ID_GROUP                        32807
#define ID_EDIT_UNGROUP                 32808
#define ID_UNGROUP                      32809
#define ID_PLAN_ADDNEWGOAL              32810
#define ID_PLAN_EDITTHISITEM            32811
#define ID_PLAN_INSERTSUBITEM           32812
#define ID_PLAN_DELETE                  32813
#define ID_VIEW_GRID                    32814
#define ID_VIEW_ALIGNTOGRID             32815
#define ID_ALIGNTOGRID                  32816
#define ID_WINDOW_MINIMIZERIGHT         32817
#define ID_PLAN_HELP_WHATSWRONG         32818
#define ID_GET_PROC_HELP                32819
#define ID_NEW_VARIABLE                 32820
#define ID_VARIABLE_LIST                32821
#define ID_POPUP_EXPLAIN                32822
#define ID_PLAN_TEMPLATE                32823
#define ID_PLAN_SUBMIT                  32824
#define ID_DIAGRAM_TOGGLEGROUP          32825
#define ID_CHOICE_ITEM                  32826
#define ID_PLAN_DONE                    32827
#define ID_EDIT_AUTHORPROPERTIES        32828
#define ID_AUTHORPROPS                  32829
#define ID_HELP_SHOWLESSON              32830
#define ID_SHOWLESSON                   32831
#define ID_MC_QUESTION                  32832
#define ID_FILE_SHOWRULEDLG             32833
#define ID_SHOWRULEDLG                  32834
#define IDC_PHYS_REVIEW_EQN             32835
#define ID_PHYS_REVIEW_EQN              32836
#define ID_VIEW_FONT                    32837
#define ID_2DMOTION                     32838
#define ID_POPUP_ADDNEWVARIABLE         32839
#define ID_MODIFY_VARIABLE              32840
#define ID_DELETE_VARIABLE              32841
#define ID_VARIABLE_WHATSWRONG          32842
#define ID_VARIABLE_NEW                 32843
#define ID_VARIABLE_MODIFY              32844
#define ID_HELP_DRAWFORCE               32900
#define ID_HELP_DRAWVELOCITY            32901
#define ID_HELP_DRAWACCELERATION        32902
#define ID_HELP_DRAWBODY                32903
#define ID_TRAINBODY                    32904
#define ID_TRAINFORCE                   32905
#define ID_TRAINVELOCITY                32906
#define ID_TRAINACCELERATION            32907
#define ID_TBODY_TOOL                   32908
#define ID_TBODY_DLG                    32909
#define ID_TBODY_LABEL                  32910
#define ID_TBODY_BODY                   32911
#define ID_TBODY_TIME                   32912
#define ID_TFORCE_TOOL                  32919
#define ID_TFORCE_BDOWN                 32920
#define ID_TFORCE_DLG                   32921
#define ID_TFORCE_TIME                  32922
#define ID_TFORCE_LABEL                 32923
#define ID_TFORCE_BODY                  32924
#define ID_TFORCE_DIRECTION             32925
#define ID_TFORCE_TYPE                  32926
#define ID_TFORCE_AGENT                 32927
#define ID_TVELOCITY_TOOL               32929
#define ID_TVELOCITY_BDOWN              32930
#define ID_TVELOCITY_DLG                32931
#define ID_TVELOCITY_TIME               32932
#define ID_TVELOCITY_LABEL              32933
#define ID_TVELOCITY_DIRECTION          32935
#define ID_TVELOCITY_BODY               32938
#define ID_TACCELERATION_TOOL           32939
#define ID_TACCELERATION_BDOWN          32940
#define ID_TACCELERATION_DLG            32941
#define ID_TACCELERATION_TIME           32942
#define ID_TACCELERATION_LABEL          32943
#define ID_TACCELERATION_DIRECTION      32945
#define ID_TACCELERATION_BODY           32948
#define ID_TRAINRULER                   32949
#define ID_TRULER_TOOL                  32950
#define ID_TRULER_BDOWN                 32951
#define ID_TRULER_DLG                   32952
#define ID_TMOTACC_TIME                 32953
#define ID_HELP_DRAWMOTIONBODY          32955
#define ID_HELP_DRAWPOSITION            32956
#define ID_TRAINPOSITION                32957
#define ID_TPOSITION_TOOL               32958
#define ID_HELP_DRAWMOTVEL              32959
#define ID_TRAINMOTVEL                  32960
#define ID_TMOTVEL_TOOL                 32961
#define ID_TMOTVEL_BDOWN                32962
#define ID_HELP_DRAWMOTACC              32963
#define ID_TRAINMOTACC                  32964
#define ID_TMOTACC_TOOL                 32965
#define ID_TMOTACC_BDOWN                32966
#define ID_TRULER_BODY                  32969
#define ID_TRULER_DTIME                 32970
#define ID_TRULER_MTIME                 32971
#define ID_TRULER_INTERVAL              32972
#define ID_TRULER_UNITS                 32973
#define ID_DRAWMOTIONBODY               32974
#define ID_DRAWPOSITION                 32975
#define ID_DRAWMOTVEL                   32976
#define ID_DRAWMOTACC                   32977
#define ID_ENDMOTIONDGRM                32978
#define ID_FILE_SHOWDEMO                32979
#define ID_VIEW_PTR                     32980
#define ID_VIEW_PTR_DLG                 32981
#define ID_ADDSYMBOL                    32982
#define ID_HINTBTN_FIRST                32986
#define ID_HINTBTN_HINT                 32986
#define ID_FOLLOWUP_HOW                 32987
#define ID_FOLLOWUP_EXPLAIN             32988
#define ID_FOLLOWUP_WHY                 32989
#define ID_HINTBTN_WHATSWRONG           32990
#define ID_FOLLOWUP_HIDE                32991
#define ID_HINTBTN_LAST                 32991
#define ID_VIEW_HIDE_HINT               32992
#define ID_OBJECT_MOVETOFRONT           32993
#define ID_OBJECT_MOVETOBACK            32994
#define ID_OBJECT_MOVEFORWARD           32995
#define ID_OBJECT_MOVEBACK              32996
#define ID_HYPERTEXT                    33045
#define ID_PLAYER_REPLAY_HELP           33046
#define ID_PLAYER_QUIT_DEMO             33047
#define ID_HELP_DRAWDISPLACEMENT        33049
#define ID_TRAINDISPLACEMENT            33050
#define ID_PLAYER_GOTO                  33050
#define ID_TDISPLACEMENT_TOOL           33051
#define ID_TDISPLACEMENT_BDOWN          33052
#define ID_TDISPLACEMENT_DLG            33053
#define ID_TDISPLACEMENT_TIME           33054
#define ID_NEWTONSFIRST                 33054
#define ID_TDISPLACEMENT_LABEL          33055
#define ID_NEWTONSSECOND                33055
#define ID_KINEMATICS                   33056
#define ID_TDISPLACEMENT_DIRECTION      33057
#define ID_ENERGY                       33057
#define ID_WORK                         33058
#define ID_TDISPLACEMENT_BODY           33060
#define ID_SOUGHT_FIRST                 33096
#define ID_SOUGHT_FORCEMAG              33096
#define ID_SOUGHT_ACCMAG                33097
#define ID_SOUGHT_VELMAG                33098
#define ID_SOUGHT_DISPMAG               33099
#define ID_SOUGHT_RADIUS                33100
#define ID_COMMENT                      33101
#define ID_SOUGHT_COMPRESSION           33101
#define ID_TEXTBOOK                     33102
#define ID_SOUGHT_DISTANCE              33102
#define ID_SOUGHT_DISTTRAV              33103
#define ID_SOUGHT_MASS                  33104
#define ID_SOUGHT_SPEED                 33105
#define ID_SOUGHT_TIME                  33106
#define ID_VARIABLE_ENDLIST             33107
#define ID_SOUGHT_FORCEDIR              33107
#define ID_SOUGHT_ACCDIR                33108
#define ID_SOUGHT_VELDIR                33109
#define ID_SOUGHT_DISPDIR               33110
#define ID_SOUGHT_LAST                  33110
#define ID_ADDPROP_FIRST                33114
#define ID_ADDPROP_FORCE                33114
#define ID_ADDPROP_KINEMATICFIRST       33115
#define ID_ADDPROP_ACCELERATION         33115
#define ID_ADDPROP_VELOCITY             33116
#define ID_ADDPROP_DISPLACEMENT         33117
#define ID_ADDPROP_TIME                 33118
#define ID_ADDPROP_KINEMATICLAST        33118
#define ID_ADDPROP_MASS                 33119
#define ID_ADDPROP_RADIUS               33120
#define ID_ADDPROP_GRAVACC              33121
#define ID_ADDPROP_COEFFRICTION         33122
#define ID_ADDPROP_LAST                 33123
#define ID_ADD_HELP_FILE                33124
#define ID_PLAYER_STEP                  33130
#define ID_ADD_OPTION                   33131
#define ID_PROBLEMSET_DELETE            33132
#define ID_PROBSET_ADD_PROB             33133
#define ID_PROBSET_ADD_OPT              33134
#define ID_PROBSET_DELETE_PROB          33136
#define ID_PROBSET_DELETE_OPTION        33137
#define ID_PRINCIPLE_ADD                33138
#define ID_PRINCIPLE_DELETE             33139
#define ID_GREEK                        33146
#define ID_SOLVEFOR                     33147
#define ID_FILE_OPENPROBLEMSET          33148
#define ID_OPEN_PROBLEM                 33149
#define ID_FILE_EDIT_PROBSET            33150
#define ID_DELETE_SOLUTION              33150
#define ID_VARIABLE_SOLVEFOR            33152
#define ID_DIALOG_WHATSWRONG            33153
#define ID_PRINCIPLE_CHECK              33154
#define ID_PRINCIPLE_UNCHECK            33155
#define ID_PRINCIPLE_MODIFY             33156
#define ID_POPUP_SOLVEFOR               33158
#define ID_VARIABLE_ADDNEW              33169
#define ID_PROBLEMSET_MOVEUP            33171
#define ID_PROBSET_MOVEUP               33172
#define ID_PROBLEMSET_MOVEDOWN          33173
#define ID_PROBSET_MOVEDOWN             33174
#define ID_ZDIR_FIRSTCMD                33175
#define ID_ZDIR_MENU                    33175
#define ID_ZDIR_FIRST                   33176
#define ID_ZDIR_NONE                    33176
#define ID_ZDIR_INTO                    33177
#define ID_ZDIR_OUTOF                   33178
#define ID_ZDIR_LAST                    33178
#define ID_ZDIR_LASTCMD                 33178
#define ID_PLAYER_SNAPSHOT              33180
#define ID_WEB_SUPPORT                  33189
#define ID_EDIT_INSERTPICTURE           33190
#define ID_INSERTPICTURE                33191
#define ID_DRAWVECTOR_FORC              33196
#define ID_HELP_VIEWTRAININGVIDEOS      33218
#define ID_HELP_VIDEOS                  33219
#define ID_HELP_REVIEWUNITS             33220
#define ID_HELP_UNITS                   33221
#define ID_TVELOCITY_TYPE               33222
#define ID_HELP_EMAILANDESTEAM          33222
#define ID_HELP_EMAIL                   33223
#define ID_DRAWVECTOR_IMPUSE            33224
#define ID_TACCELERATION_TYPE           33232
#define ID_VARIABLE_ADDFIRST            41000
#define ID_VARIABLE_ADDFORCE            41001
#define ID_VARIABLE_LINVECTOR_FIRST     41002
#define ID_VARIABLE_ADDACCELERATION     41002
#define ID_VARIABLE_ADDVELOCITY         41003
#define ID_VARIABLE_ADDDISPLACEMENT     41004
#define ID_VARIABLE_ADDMOMENTUM         41005
#define ID_VARIABLE_LINVECTOR_LAST      41005
#define ID_VARIABLE_ADDRADIUS           41006
#define ID_VARIABLE_ADDCOMPRESSION      41007
#define ID_VARIABLE_ADDDISTANCE         41008
#define ID_VARIABLE_ADDDISTTRAV         41009
#define ID_VARIABLE_ADDMASS             41010
#define ID_VARIABLE_ADDSPEED            41011
#define ID_VARIABLE_ADDTIME             41012
#define ID_VARIABLE_ADDANGLE            41013
#define ID_VARIABLE_ADDWORK             41014
#define ID_VARIABLE_ADDPOWER            41015
#define ID_VARIABLE_ADDNRG              41016
#define ID_VARIABLE_ADDSPRINGCONST      41017
#define ID_VARIABLE_ADDHEIGHT           41018
#define ID_VARIABLE_ANGVECTOR_FIRST     41019
#define ID_VARIABLE_ADDANGACCELERATION  41019
#define ID_VARIABLE_ADDANGVELOCITY      41020
#define ID_VARIABLE_ADDANGDISPLACEMENT  41021
#define ID_VARIABLE_ADDANGMOMENTUM      41022
#define ID_VARIABLE_ANGVECTOR_LAST      41022
#define ID_VARIABLE_ADDMOMINERTIA       41023
#define ID_VARIABLE_ADDLENGTH           41024
#define ID_VARIABLE_ADDWIDTH            41025
#define ID_VARIABLE_ADDTORQUE           41026
#define ID_VARIABLE_ADDRELPOS           41027
#define ID_VARIABLE_ADDFRICTIONCOEF     41028
#define ID_VARIABLE_ADDPERIOD           41029
#define ID_VARIABLE_ADDCURRENT          41030
#define ID_VARIABLE_ADDVOLTAGE          41031
#define ID_VARIABLE_ADDRESISTANCE       41032
#define ID_VARIABLE_ADDCAPACITANCE      41033
#define ID_VARIABLE_ADDCHARGE           41034
#define ID_VARIABLE_ADDRELVEL           41035
#define ID_VARIABLE_ADDEFIELD           41036
#define ID_VARIABLE_ADDPOTENTIAL        41037
#define ID_VARIABLE_ADDSTOREDENERGY     41038
#define ID_VARIABLE_ADDBFIELD           41039
#define ID_VARIABLE_ADDINDUCTANCE       41040
#define ID_VARIABLE_ADDCURRENTCHANGE    41041
#define ID_VARIABLE_ADDTIMECONSTANT     41042
#define ID_VARIABLE_ADDELECTRICPOWER    41043
#define ID_VARIABLE_ADDFOCALLENGTH      41044
#define ID_VARIABLE_ADDOBJECTDISTANCE   41045
#define ID_VARIABLE_ADDIMAGEDISTANCE    41046
#define ID_VARIABLE_ADDMAGNIFICATION    41047
#define ID_VARIABLE_ADDCURVATURE        41048
#define ID_VARIABLE_ADDLENSDISTANCE     41049
#define ID_VARIABLE_ADDIMPULSE          41050
#define ID_VARIABLE_ADDPROBABILITY      41051
#define ID_VARIABLE_MAX_STATIC          41100
#define ID_VARIABLE_ADDLAST             41200
#define ID_DRAWVECTOR_FIRST             45000
#define ID_DRAWVECTOR_FORCE             45000
#define ID_DRAWVECTOR_VELOCITY          45001
#define ID_DRAWVECTOR_ACCELERATION      45002
#define ID_DRAWVECTOR_COMPONENT         45003
#define ID_DRAWVECTOR_DISPLACEMENT      45004
#define ID_DRAWVECTOR_MOMENTUM          45005
#define ID_DRAWVECTOR_RELPOS            45006
#define ID_DRAWVECTOR_TORQUE            45007
#define ID_DRAWVECTOR_RELVEL            45008
#define ID_DRAWVECTOR_EFIELD            45009
#define ID_DRAWVECTOR_BFIELD            45010
#define ID_DRAWVECTOR_IMPULSE           45011
#define ID_DRAWVECTOR_LAST              45011
#define ID_DRAWTOOL_FIRST               50000
#define ID_DRAW_VECTOR                  50000
#define ID_DIAGRAM_COORDINATES          50001
#define ID_SYSTEM                       50002
#define ID_LABEL                        50003
#define ID_ANGLE                        50004
#define ID_SELECT                       50005
#define ID_GUIDE_LINE                   50006
#define ID_RECTANGLE                    50007
#define ID_ROUNDRECT                    50008
#define ID_ELLIPSE                      50009
#define ID_LINE                         50010
#define ID_ARC                          50011
#define ID_ARC2                         50012
#define ID_POLYGON                      50013
#define ID_POLYBEZIER                   50014
#define ID_RULER                        50015
#define ID_MOTION_BODY                  50016
#define ID_DOC_AREA                     50017
#define ID_LABEL_RADIUS                 50018
#define ID_DRAWTOOL_LAST                50018
#define IDM_GREEKLETTER_FIRST           50258
#define IDM_ALPHA                       50258
#define IDM_BETA                        50259
#define IDM_GAMMA                       50260
#define IDM_DELTA                       50261
#define IDM_EPSILON                     50262
#define IDM_ZETA                        50263
#define IDM_ETA                         50264
#define IDM_THETA                       50265
#define IDM_IOTA                        50266
#define IDM_KAPPA                       50267
#define IDM_LAMBDA                      50268
#define IDM_MU                          50269
#define IDM_NU                          50270
#define IDM_XI                          50271
#define IDM_OMICRON                     50272
#define IDM_PI                          50273
#define IDM_RHO                         50274
#define IDM_SIGMA                       50275
#define IDM_TAU                         50276
#define IDM_UPSILON                     50277
#define IDM_PHI                         50278
#define IDM_CHI                         50279
#define IDM_PSI                         50280
#define IDM_OMEGA                       50281
#define IDM_GREEKLETTER_LAST            50281
#define ID_DIRECTION_FIRST              50300
#define ID_VERTICAL                     50300
#define ID_HORIZONTAL                   50301
#define ID_VERTANDHORZ                  50302
#define ID_PARALLEL_FIRST               50303
#define ID_OTHER                        50303
#define ID_TWO_OTHER                    50304
#define ID_PARALLEL_LAST                50304
#define ID_DIRECTION_LAST               50305
#define ID_NEXT_FIRST                   50306
#define ID_WEREDONE                     50306
#define ID_CANCELUNKNOWN                50307
#define ID_SUBSTAGE                     50308
#define ID_NEWSTAGE                     50309
#define ID_NEXT_LAST                    50309
#define ID_FILE_OPENSOLUTION            57666
#define ID_INDICATOR_ANGLE              59142
#define ID_INDICATOR_SCORE              59143
#define IDW_AUTHORBAR                   0xE805
#define ID_VIEW_AUTHORBAR               0xE805
#define IDW_PROBLEMBAR                  0xE806
#define ID_VIEW_PROBLEMBAR              0xE806
#define IDW_EQBAR                       0xE807
#define ID_VIEW_EQBAR                   0xE807
#define ID_SOLVEFOR_MENU                60000
#define ID_SOLVEFOR_FIRST               60001
#define ID_SOLVEFOR_LAST                60500

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        395
#define _APS_NEXT_COMMAND_VALUE         33225
#define _APS_NEXT_CONTROL_VALUE         1423
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
