//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Expmenu.rc
//
#define IDR_POPUP_EXPLAIN               131
#define ID_EXP_FIRST                    40001
#define ID_EXP_WHY_NEEDED               40001
#define ID_EXP_CHOICE                   40002
#define ID_EXP_JUSTIFY                  40003
#define ID_EXP_MAG                      40004
#define ID_EXP_DIR                      40005
#define ID_EXP_ROLE                     40006
#define ID_EXP_SOURCE                   40008
#define ID_SINGLE_BODY                  40009
#define ID_COMPOUND_BODY                40010
#define ID_TENSION                      40011
#define ID_NORMAL                       40012
#define ID_WEIGHT                       40013
#define ID_EXP_EQUATION                 40014
#define ID_EXP_LAST                     40030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8168
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         8001
#define _APS_NEXT_SYMED_VALUE           8101
#endif
#endif
