ALTER TABLE `REVIEWED_PROBLEMS`
  MODIFY COLUMN `userName` varchar(50) NOT NULL,
  MODIFY COLUMN `adminName` varchar(50) NOT NULL;
CREATE USER 'open'@'localhost';

GRANT SELECT,INSERT,UPDATE,DELETE ON REVIEWED_PROBLEMS TO 'open'@'localhost';
GRANT SELECT,INSERT,UPDATE,DELETE ON STUDENT_DATASET TO 'open'@'localhost';
